#!/usr/bin/env node

try {
  require('@strv/shh')
} catch (err) {
  // Unknown error.
  if (!(err instanceof Error || err.message.includes("Cannot find module '@strv/shh'"))) {
    throw err
  }

  // Load local path – used during testing, and in on the example application.
  require(require('path').resolve(__dirname, './dist'))
}
